services:
  postgres:
    image: postgres:latest
    container_name: postgres_library_v2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_v2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:

